DROP TABLE IF EXISTS TBL_EMPLOYEEDETAILS;
  
CREATE TABLE TBL_EMPLOYEEDETAILS (
  empId INT PRIMARY KEY,
  empName VARCHAR(250) NOT NULL,
  emailId VARCHAR(250) NOT NULL,
  departmentName VARCHAR(250) DEFAULT NULL
);